package com.giftedlabs.echoinhealthbackend.entity;

public enum ScanType {
    ABDOMINAL,
    ABDOMEN_PELVIS_MALE,
    ABDOMEN_PELVIS_FEMALE,
    PELVIC_MALE,
    PELVIC_FEMALE,
    OBSTETRIC_EARLY,
    OBSTETRIC_LATE,
    OBSTETRIC_TWINS,
    ANOMALY,
    BIOPHYSICAL_PROFILE,
    TRANSABDOMINAL_PELVIC,
    TRANSVAGINAL,
    ECHO_ADULT,
    ECHO_PEDIATRIC,
    MUSCULOSKELETAL,
    NECK,
    THYROID,
    BREAST,
    CHEST,
    SCROTAL,
    PENILE,
    NEONATAL_HEAD,
    ARTERIAL_DOPPLER_BOTH_LOWER,
    ARTERIAL_DOPPLER_LEFT_LOWER,
    ARTERIAL_DOPPLER_RIGHT_LOWER,
    ARTERIAL_DOPPLER_LEFT_UPPER,
    ARTERIAL_DOPPLER_RIGHT_UPPER,
    VENOUS_DOPPLER_BOTH_LOWER,
    VENOUS_DOPPLER_LEFT_LOWER,
    VENOUS_DOPPLER_RIGHT_LOWER,
    VENOUS_DOPPLER_LEFT_UPPER,
    VENOUS_DOPPLER_RIGHT_UPPER,
    GENERAL;

    public boolean isDoppler() {
        return name().contains("DOPPLER");
    }

    public boolean isGeneral() {
        return this == GENERAL;
    }
}
